services:
  - type: web
    name: redskord
    env: node
    plan: free
    buildCommand: npm install --only=production
    startCommand: node server/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /


